version: '1'
services:
  adaGateway:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "58120:5000"
    depends_on:
      - redis
    restart: always
    links:
      - redis
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
      - "58121:58121"
    command:  -A tasks --port=58121 --broker=redis://redis:6379/0
    depends_on:
      - redis
    restart: always
  redis:
    image: redis